### ISSUE TITLE
Failed to build on win64 with v1.4.4

### ISSUE THREAD

**Issue by idejie** [openbci-archive/OpenBCI_Hub#103]
I tried to build this app on [appveyor](https://ci.appveyor.com/) with [v1.4.4](https://github.com/openbci-archive/OpenBCI_Hub/tree/v1.4.4).
Because I saw the file `appveyor.yml` in the repo.

But encountered some problems when installing `app` dependencies:
```
gyp ERR! configure error 
gyp ERR! stack Error: 403 status code downloading arm64 iojs.lib
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:335:22)
gyp ERR! stack     at emitOne (events.js:121:20)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1066:10)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:454:20)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\openbci-ganglion-electron\app\node_modules\@serialport\bindings
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules\noble\node_modules\xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN openbci-electron-hub@1.4.4 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2020-07-09T04_38_14_620Z-debug.log
    at ChildProcess.childProcess.once.code (C:\projects\openbci-ganglion-electron\node_modules\electron-builder\src\util\util.ts:154:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at spawn (C:\projects\openbci-ganglion-electron\node_modules\electron-builder\src\util\util.ts:117:3)
    at spawnNpmProduction (C:\projects\openbci-ganglion-electron\node_modules\electron-builder\src\util\util.ts:46:3)
    at Object.installDependencies (C:\projects\openbci-ganglion-electron\node_modules\electron-builder\src\util\util.ts:20:122)
    at C:\projects\openbci-ganglion-electron\node_modules\electron-builder\src\install-app-deps.ts:30:2
    at Generator.next (<anonymous>)
From previous event:
    at tsAwaiter (C:\projects\openbci-ganglion-electron\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at main (C:\projects\openbci-ganglion-electron\node_modules\electron-builder\src\install-app-deps.ts:23:3)
    at Object.<anonymous> (C:\projects\openbci-ganglion-electron\node_modules\electron-builder\src\install-app-deps.ts:35:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```
full log: [log_openbci_hub_v1.4.4.txt](https://github.com/openbci-archive/OpenBCI_Hub/files/4894562/log_openbci_hub_v1.4.4.txt)

**Comment by idejie** [comment]
I tried to update the `node-gyp` to **5.1.0**, and soleved.
```
- npm install node-gyp@5.1.0 -g
- npm config set node_gyp "C:\Users\appveyor\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js"
```

**Comment by idejie** [comment]
Then I tried to build the repo in my VM - Win10.
```cmd
> node --version
v8.17.0
> npm --version
6.13.4
> node-gyp --version
v5.1.0
>SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
>PATH
PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;C:\Python27\;C:\Python27\Scripts;C:\Program Fi.............
>SET GYP_MSVS_VERSION=2013
> npm install --build-from-source
```
But still encountered some problems when installing app dependencies:
```
Unhandled rejection Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> @serialport/bindings@2.0.8 install C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\app\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild


C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\app\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Users\idejie\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\idejie\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

Error output:
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onread (net.js:622:25)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\idejie\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\app\node_modules\@serialport\bindings
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN openbci-electron-hub@1.4.4 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules\xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\idejie\AppData\Roaming\npm-cache\_logs\2020-07-09T07_14_09_866Z-debug.log

    at ChildProcess.childProcess.once.code (C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\node_modules\electron-builder\src\util\util.ts:154:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at spawn (C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\node_modules\electron-builder\src\util\util.ts:117:3)
    at spawnNpmProduction (C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\node_modules\electron-builder\src\util\util.ts:46:3)
    at Object.installDependencies (C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\node_modules\electron-builder\src\util\util.ts:20:122)
    at C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\node_modules\electron-builder\src\install-app-deps.ts:30:2
    at Generator.next (<anonymous>)
From previous event:
    at tsAwaiter (C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at main (C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\node_modules\electron-builder\src\install-app-deps.ts:23:3)
    at Object.<anonymous> (C:\Users\idejie\Desktop\OpenBCI_Hub-1.4.4\node_modules\electron-builder\src\install-app-deps.ts:35:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```
